version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bancodados_api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=junior
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mbancodados_apio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: junior
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data